name: Version Bump

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changesets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
